version: '3.8'

services:
  api:
    image: tenantapi:prod
    container_name: tenantapi
    env_file:
      - ./env/api/.env
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - tenant
  database:
    image: postgres
    container_name: database
    env_file:
      - ./env/db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - tenant
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - ./env/pgAdmin/.env
    ports:
      - "5050:80"
      - "5432"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    user: "5050:5050"
    networks:
      - tenant

networks:
  tenant:
    driver: bridge