FROM golang:1.21

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum first to cache dependencies
COPY go.mod go.sum ./

# Install dependencies
RUN go mod tidy

RUN go get github.com/jackc/pgx/v5/pgconn@v5.5.5

# Copy the rest of the application code
COPY . .

ENTRYPOINT [ "go" ]
CMD [ "run", "./api" ]