version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-tenant
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tenants
      - DB_PORT=5432
      - GITHUB_CLIENT_ID=Ov23liqCWXLsBMtqEUaM
      - GITHUB_CLIENT_SECRET=a14ea7a80a8720de2683e1f1e2eedc3f8459a40a
      - JWT_SECRET=544c142b11d962494bc6d7ecffcd53c94862bb849f0c245ae8bb9715b10a03c6
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - tenant
  
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenants
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tenant

networks:
  tenant:
    driver: bridge